version: "3.9"  # optional since v1.27.0
services:
  db:
    image: mariadb:10.5.12
    restart: always
    ports: 
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 9999:8080
  api:
    image: eliasdebaveye/01_expressbirds
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - docker.ormconfig.env
    environment:
      NODE_ENV: Production
    